# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

dt = 0.003		 #Sampling
N = 7		 #Prediction horizon
u_lb = [[-4.6234]] 		 # Lower input constraint
u_ub = [[5.3766]] 		 # Upper input constraint

Ad = [
	[ 1, -1, -0, -0],
	[ 0, 1.00963139, 0.00302195789, -0.000647493758],
	[ 0, 6.44332069, 1.02053755, -0.335878758],
	[ 0, -0.0954516528, -0.0232225051, 0.162457879],
	]

Bd = [[ 0],[ -2.07975654e-06],[ -0.00183802608],[ 0.00389551218],]

Q = [
	[ 200, 0, 0, 0],
	[ 0, 1000, 0, 0],
	[ 0, 0, 100, 0],
	[ 0, 0, 0, 10],
	]

R = [[0.01]]
P = "auto" 		 # End penalty