# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

dt = 0.003		 #Sampling
N = 7		 #Prediction horizon
u_lb = [[-4.6234]] 		 # Lower input constraint
u_ub = [[5.3766]] 		 # Upper input constraint

Ad = [
	[ 1, -1, -0, -0],
	[ 0, 1.00963287, 0.00302193111, -0.000647594865],
	[ 0, 6.44427897, 1.02051402, -0.335929795],
	[ 0, -0.0952330093, -0.0231655632, 0.162447919],
	]

Bd = [[ 0],[ -2.08005346e-06],[ -0.00183828647],[ 0.00389543638],]

Q = [
	[ 200, 0, 0, 0],
	[ 0, 1000, 0, 0],
	[ 0, 0, 100, 0],
	[ 0, 0, 0, 10],
	]

R = [[0.01]]
P = "auto" 		 # End penalty