// Arduino AVR Compatible Vector Header
// Automatically generated by the AutomationShield library.
// Visit www.automationshield.com for more information.
// ========================================================

#ifndef I2DAC_H
#define I2DAC_H

#include <avr/pgmspace.h>
#define I2DAC_length 4
const PROGMEM float I2DAC[I2DAC_length]={0.0049535007,
 -0.272750813,
 75.535553,
 -6.0818204};
#endif
