// Arduino AVR Compatible Vector Header
// Automatically generated by the AutomationShield library.
// Visit www.automationshield.com for more information.
// ========================================================

#ifndef U2DAC_H
#define U2DAC_H

#include <avr/pgmspace.h>
#define U2DAC_length 4
const PROGMEM float U2DAC[U2DAC_length]={1.41353993,
 -15.4070873,
 389.266686,
 -11.7613432};
#endif
