%   Creates a problem definition file for the muAOMPC model
%   predictive control package
%
%   The function requires a file name that will be written as a Python
%   script. This file name refers to the problem itself, the script 
%   generates a main file for the muAOMPC package, thus appends "_Main"
%   to the filename.
%
%   This code is part of the AutomationShield hardware and software
%   ecosystem. Visit http://www.automationshield.com for more
%   details. This code is licensed under a Creative Commons
%   Attribution-NonCommercial 4.0 International License.
%
%   Created by:     Gergely Takács and Erik Mikuláš
%   Created on:     9.9.2020
%   Last update on: 8.8.2023

function muAOMPC_Main(fileName)
  
    filehandle = fopen([fileName, '_muAOMPC_Main.py'], 'wt');

    fprintf(filehandle, ['# MPC problem definition file for muaOMPC in Python\n']);
    fprintf(filehandle, ['# Automatically generated by the AutomationShield library.\n']);
    fprintf(filehandle, ['# Visit www.automationshield.com for more information.\n']);
    fprintf(filehandle, ['# ========================================================\n']);
    fprintf(filehandle, '\n');

    fprintf(filehandle, ['from muaompc import ldt']);
    fprintf(filehandle, '\n');
    fprintf(filehandle, ['mpc = ldt.setup_mpc_problem("',fileName,'.prb",numeric="float32")']);
    fprintf(filehandle, '\n');
    fprintf(filehandle, ['ldt.generate_mpc_data(mpc,"',fileName,'.dat")']);
    fclose(filehandle);

    disp(['MPC problem main file for muAOMPC is: "', fileName, '.py".'])
end