%   Creates a problem definition file for the muAOMPC model
%   predictive control package
%
%   The function requires a file name that will be written as a Python
%   script. Next, the user needs to input the state and input matrices
%   from the linear state-space model, state penalty and input penalty
%   matrices, sampling time, prediction horizon and minimal and maximal
%   input constraints. The file can then be supplied to the muAOMPC 
%   package (http://ifatwww.et.uni-magdeburg.de/syst/muAO-MPC/) to generate
%   a fully functional MPC problem. 
%
%   This code is part of the AutomationShield hardware and software
%   ecosystem. Visit http://www.automationshield.com for more
%   details. This code is licensed under a Creative Commons
%   Attribution-NonCommercial 4.0 International License.
%
%   Created by:     Gergely Takács
%   Created on:     9.9.2020
%   Last update on: 9.9.2020

function muAOMPC_Problem(fileName, Ad, Bd, Q, R, dt, N, umin, umax)
    
    filehandle = fopen([fileName, '.py'], 'wt');

    fprintf(filehandle, ['# MPC problem definition file for muaOMPC in Python\n']);
    fprintf(filehandle, ['# Automatically generated by the AutomationShield library.\n']);
    fprintf(filehandle, ['# Visit www.automationshield.com for more information.\n']);
    fprintf(filehandle, ['# ========================================================\n']);
    fprintf(filehandle, '\n');

    fprintf(filehandle, ['dt = ', num2str(dt), '\t\t #Sampling\n']);
    fprintf(filehandle, ['N = ', num2str(N), '\t\t #Prediction horizon\n']);

    fprintf(filehandle, ['u_lb = [[', num2str(umin), ']] \t\t # Lower input constraint\n']);
    fprintf(filehandle, ['u_ub = [[', num2str(umax), ']] \t\t # Upper input constraint\n']);

    matrixToPython(filehandle, Ad);
    matrixToPython(filehandle, Bd);
    matrixToPython(filehandle, Q);
    matrixToPython(filehandle, R);
    fprintf(filehandle, '\n');
    fprintf(filehandle, ['P = "auto" \t\t # End penalty']);
    fclose(filehandle);

    disp(['Problem exported to "', fileName, '.py".'])
end