function [y,u] = import_ident_data(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  VALDATA = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  VALDATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  valdata = importfile1("C:\Users\Erik\Documents\Arduino\libraries\AutomationShield\matlab\examples\AeroShield\val_data.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Aug-2023 11:29:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["y", "u"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
valdata = readtable(filename, opts);

%% Convert to output type
valdata = table2array(valdata);

y = valdata(:,1);
u = valdata(:,2);
end