# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

dt = 0.003		 #Sampling
N = 20		 #Prediction horizon
u_lb = [[-5.0056]] 		 # Lower input constraint
u_ub = [[4.9944]] 		 # Upper input constraint

Ad = [
	[ 1, -1, -0, -0],
	[ 0, 1.00447557, 0.00299584804, -0.000452342641],
	[ 0, 2.98195387, 0.996785167, -0.238253275],
	[ 0, 0.0469593367, 0.0248491858, 0.185923669],
	]

Bd = [[ 0],[ -1.31267634e-06],[ -0.00116992609],[ 0.00377224463],]

Q = [
	[ 800, 0, 0, 0],
	[ 0, 240, 0, 0],
	[ 0, 0, 260, 0],
	[ 0, 0, 0, 80],
	]

R = [[0.01]]
P = "auto" 		 # End penalty