# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

dt = 0.005		 #Sampling
N = 7		 #Prediction horizon
u_lb = [[-4.6234]] 		 # Lower input constraint
u_ub = [[5.3766]] 		 # Upper input constraint

Ad = [
	[ 1, -1, -0, -0],
	[ 0, 1.02690885, 0.0050909162, -0.0013790709],
	[ 0, 10.8548749, 1.05015613, -0.38763472],
	[ 0, -0.203462393, -0.0268220118, 0.0543527831],
	]

Bd = [[ 0],[ -7.78457143e-06],[ -0.00391469378],[ 0.0044485252],]

Q = [
	[ 50, 0, 0, 0],
	[ 0, 1000, 0, 0],
	[ 0, 0, 100, 0],
	[ 0, 0, 0, 10],
	]

R = [[0.01]]
P = "auto" 		 # End penalty