# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

import muaompc
mpc = muaompc.ltidt.setup_mpc_problem("MagnetoShield")
mpc.generate_c_files(numeric="float32")