# MPC problem definition file for muaOMPC in Python
# Automatically generated by the AutomationShield library.
# Visit www.automationshield.com for more information.
# ========================================================

dt = 0.005		 #Sampling
N = 3		 #Prediction horizon
u_lb = [[-4.6234]] 		 # Lower input constraint
u_ub = [[5.3766]] 		 # Upper input constraint

Ad = [
	[ 1, -1, -0, -0],
	[ 0, 1.02691221, 0.00509077766, -0.00137923634],
	[ 0, 10.8561017, 1.05008671, -0.387672032],
	[ 0, -0.202825614, -0.0267336835, 0.0543249081],
	]

Bd = [[ 0],[ -7.78554189e-06],[ -0.00391515073],[ 0.00444830751],]

Q = [
	[ 50, 0, 0, 0],
	[ 0, 100, 0, 0],
	[ 0, 0, 10, 0],
	[ 0, 0, 0, 1],
	]

R = [[0.01]]
P = "auto" 		 # End penalty